### ISSUE TITLE
[Question] Can I use this in replace of wee_alloc?

### ISSUE THREAD

**Issue by katopz** [MaderNoob/galloc#14]
Not sure it's just work for wasm like [wee_alloc](https://github.com/rustwasm/wee_alloc) or need some extra work?

**Comment by MaderNoob** [comment]
It will work, but `wee_alloc` is a growing heap that will grow when it runs out of memory, and `galloc` is a heap allocator that was designed to be used in kernels, which means that the size of the heap is constant and the heap does not grow automatically when exhausted.

So you can indeed use it, but the heap's size will be constant.
